### PR TITLE
Respuestas Guido Franco

### PR DESCRIPTION
**Pull request by guidofranco**

### CODE REVIEW

**Comment by metdinov** [comment]
Well done!

One observation:
- In exercise 5, we were asking for the _last match played_ in the tournament.

This just returns the `match_id` of the _last row_ in the dataset.
```python
>>> df.match_id.iloc[-1]
```

**Comment by guidofranco** [comment]
Thank you! I have replaced this line with `df.iloc[-1]`

**Comment by metdinov** [comment]
> Thank you! I have replaced this line with `df.iloc[-1]`

I did not make it clear enough, but what we are asking for is the last match played in the tournament. Think about chronological order (i.e. the `date` column)

**Comment by guidofranco** [comment]
I get it, sorry for my lack of understanding.
I have made changes to the same cell.
The possible ways to get such a match are:
`last_match = df[df.date == df.date.max()].match_id.iloc[0]`
`last_match = df.sort_values(by=["date"]).match_id.iloc[-1]`
`last_match = df.sort_values(by=["date"], ascending = False).match_id.iloc[-0]`

**Pull request closed without merging**
